#ifndef DEF_TRANSCRIPT_ASSEMBLY_CONFIG_H
#define DEF_TRANSCRIPT_ASSEMBLY_CONFIG_H

#define MIN_NUM_SUPPORTING_READS_FOR_SPLICE_JUNCTION 2

#define MAX_NUM_RECURSIONS 100000

#define MAX_NUM_ISOFORMS 10

#define MIN_RPKM 0.1


#endif
